"""empty message

Revision ID: 3c5c02ba0258
Revises: 1648b33e0e21
Create Date: 2017-04-22 19:27:37.350914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c5c02ba0258'
down_revision = '1648b33e0e21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_question_bonus_format', table_name='question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_question_bonus_format', 'question', ['bonus_format'], unique=False)
    # ### end Alembic commands ###
